[13.0][ADD] portal_hide_apps
solvosci/slv-general pull request #11
Opened 2022-01-21 11:19 UTC by ChristianSantamaria

Hides the default sale, purchase and account portal menus.

2022-01-27 12:25 UTC, dalonsod requested changes
For Purchase case, looking at

https://github.com/odoo/odoo/blob/13.0/addons/purchase/controllers/portal.py#L19

it's possible to simply reset `*_count` values via method inheritance, so view modification should be no longer needed. Could you check?

2022-01-27 15:36 UTC, ChristianSantamaria commented
> For Purchase case, looking at
> 
> https://github.com/odoo/odoo/blob/13.0/addons/purchase/controllers/portal.py#L19
> 
> it's possible to simply reset `*_count` values via method inheritance, so view modification should be no longer needed. Could you check?

Yes, you are correct, I added to greater than the purchase order, the sale order and account invoice

2022-02-01 16:06 UTC, dalonsod approved these changes
👍 Please attend cosmetic change and squash commits

2022-02-01 16:06 UTC, dalonsod commented on portal_hide_apps/__manifest__.py
> +    ],
Remove empty section

2022-02-02 09:54 UTC, merged