[13.0][ADD] ir_filter_security_extra
solvosci/slv-general pull request #13
Opened 2024-12-19 09:56 UTC by ChristianSantamaria

Adds a new group Filter Manager

2024-12-19 10:10 UTC, dalonsod requested changes
See comments

2024-12-19 10:10 UTC, dalonsod commented on ir_filter_security_extra/security/ir_filter_security_extra.xml
> +        <record id="group_ir_filters_manager" model="res.groups" >
A gruop shouldn't be placed in a `noupdate="1"` section.

2024-12-19 10:10 UTC, dalonsod commented on ir_filter_security_extra/security/ir_filter_security_extra.xml
> +            <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]"/>
This is already achieved, so it's not required IMO due to https://github.com/odoo/odoo/blob/4cc086d330b73514fbc64a7fcf22d8a7a9f1b691/odoo/addons/base/security/base_security.xml#L107 and https://github.com/odoo/odoo/blob/4cc086d330b73514fbc64a7fcf22d8a7a9f1b691/odoo/addons/base/security/base_groups.xml#L14-L17

2024-12-19 10:10 UTC, dalonsod commented on ir_filter_security_extra/readme/DESCRIPTION.rst
> +Adds a new group Filter Manager
Please add a little bit explanations (e.g. implications of this new group)

2024-12-19 11:53 UTC, ChristianSantamaria commented
Done, its already in test enviroment

2024-12-19 11:59 UTC, dalonsod commented
OK, I'll test ASAP

2025-01-07 08:15 UTC, dalonsod requested changes
Tested :+1: 

Only one thing:

![imagen](https://github.com/user-attachments/assets/10e060b0-6243-4ea2-806c-6ac259c019a5)


Due to a later group ID renaming, this name is not translated, could you check?

2025-01-08 06:19 UTC, ChristianSantamaria commented
Checked and fixed :+1:

2025-01-08 08:10 UTC, dalonsod approved these changes
Let's merge!

2025-01-08 08:10 UTC, merged